### PR TITLE
Updated plugin and ZIP to install plugin

### PR DESCRIPTION
**Pull request by tthatcher95**

### CODE REVIEW

**Comment by tthatcher95** [comment]
@jlaura

**Comment by jlaura** [comment]
Changes look good. Why is the zip file included here?

**Comment by tthatcher95** [comment]
I am gonna update the wiki soon, but we can use that to install the plugin to QGIS as it is being installed through Anaconda. To do that, you need a ZIP of the plugin files.

**Comment by jlaura** [comment]
We should host is somewhere else though. We don't want a zip file in the repo.

**Comment by tthatcher95** [comment]
@jlaura 10-4. It has been removed.

**Comment by jlaura** [comment]
What all is in the zip file? Because maybe we make the plugin it's own repo and then a release on here (that makes a zip and/or .tar.gz).

I agree that having the zip for the user is nice! I just want to keep the binary separated out.

**Comment by tthatcher95** [comment]
@jlaura It's just a zip of PyHAT in this repo. Nothing fancy, QGIS just takes a zip as opposed to the file directory.

**Comment by jlaura** [comment]
I'm going to merge this. I think the thing to do is to create a new repository just for the QGIS plugin. Then we can keep everything in the PyHAT folder at the root level and hit the release button on GitHub. Thoughts?

**Pull request merged**
